### ISSUE TITLE
add automatic backup

### ISSUE THREAD

**Issue by patroqueeet** [patroqueeet/darg#109]
use `https://django-dbbackup.readthedocs.io/en/stable/` and ensure we do have
- backup to dropbox
- on deploy
- daily at night (swiss timezone)
- encrypted
  explore the lib and add what you consider useful. document this.

please also provide instructions for prod setup

ensure it will raise errors with confs are missing

see deploy script for on deploy backups

**Comment by msamoylov** [comment]
I'm taking this if it's still actual.

**Comment by patroqueeet** [comment]
Deployment: add env var for path `backup` and DropboxToken to ProdDeployment

**Comment by patroqueeet** [comment]
deployed today
