### ISSUE TITLE
if user signs up and then adds another shareholder with same email: app breaks

### ISSUE THREAD

**Issue by patroqueeet** [patroqueeet/darg#113]
https://www.dropbox.com/s/ol5nkd430jhoxad/Screenshot%202016-10-20%2015.56.22.png?dl=0

shows the error from sentry. please make sure that a user who adds himself as a shareholder will have a single user instance in the database. please provide extensive coverage for for all valid use cases (get list from patroqueeet) the case that the operator is a shareholder too.

**Comment by aaslannn** [comment]
Can you detail the problem @patroqueeet?

1. Is there any way that there are multiple users with same email?
2. Can a user be deleted or suspended in the system? If so after deletion/suspension, should we allow a new user with same mail created?

**Comment by patroqueeet** [comment]
dear,

this was fixed last night with 4fa3936d4424fe7c73aa39240c74e09e8b4a1973 and 031a08a280e783cd5970f5bc4165dcf0574c2aa1.
