### ISSUE TITLE
fail on company create leaves orphan company objects

### ISSUE THREAD

**Issue by patroqueeet** [patroqueeet/darg#97]

**Comment by aaslannn** [comment]
Is this one still open :) Then I will get it.

**Comment by patroqueeet** [comment]
perfect

**Comment by patroqueeet** [comment]
symptom: I'm seeing inside the db somethimes the same company objects appear multiple times. I don't know where this comes from. but there are only a few places where companies are created. one must be the culprit.

**Comment by aaslannn** [comment]
Yeah, I have just looked at the possible places responsible for company creations.  I will look at the detail later if I can not reproduce the problem I could request an erronous db backup.

**Comment by aaslannn** [comment]
I have gone through the app and code. I find 4 cases where company is persisted or updated.

1. Default Company Add at Start page: Can not reproduce the issue as a simple save operation.
2. Update page at /company/# page: Logo upload and Updating a field did not trigger any problem,  Adding a new operator also does not cause a problem
3. Spliting shares and 4. increasing capital: Does not effect company count with my tests

@patroqueeet do you have a suggestion for another place where company is created.

**Comment by aaslannn** [comment]
Most likely as the bug title says if there is problem during creation of the company and fails and returns 500, then the database activities until that point does not rollback or the create operation should be atomic. I have tried with adding an exception case to the AddCompanySerializer create function. We should handle it.
